import { ClerkProvider } from '@clerk/nextjs';

import Header from "@/components/Header";
import ThemeProvider from "@/components/theme-provider";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Foodies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
          </ThemeProvider>
        
      </body>
    </html>
  </ClerkProvider >
  );
}
